apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "nodepoolmanager.fullname" . }}-manager-role
  labels:
  {{- include "nodepoolmanager.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - nodes/status
  verbs:
  - get
- apiGroups:
  - k8smanagers.greyridge.com
  resources:
  - nodepoolmanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8smanagers.greyridge.com
  resources:
  - nodepoolmanagers/finalizers
  verbs:
  - update
- apiGroups:
  - k8smanagers.greyridge.com
  resources:
  - nodepoolmanagers/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "nodepoolmanager.fullname" . }}-manager-rolebinding
  labels:
  {{- include "nodepoolmanager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "nodepoolmanager.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "nodepoolmanager.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'