apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "nodepoolmanager.fullname" . }}-nodepoolmanager-editor-role
  labels:
  {{- include "nodepoolmanager.labels" . | nindent 4 }}
rules:
- apiGroups:
  - k8smanagers.greyridge.com
  resources:
  - nodepoolmanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8smanagers.greyridge.com
  resources:
  - nodepoolmanagers/status
  verbs:
  - get