# permissions for end users to view nodepoolmanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: nodepoolmanager
    app.kubernetes.io/managed-by: kustomize
  name: nodepoolmanager-viewer-role
rules:
- apiGroups:
  - k8smanagers.greyridge.com
  resources:
  - nodepoolmanagers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8smanagers.greyridge.com
  resources:
  - nodepoolmanagers/status
  verbs:
  - get
