apiVersion: k8smanagers.greyridge.com/v1
kind: NodePoolManager
metadata:
  labels:
    app.kubernetes.io/name: nodepoolmanager
    app.kubernetes.io/managed-by: kustomize
  name: nodepoolmanager-sample
spec:
  subscriptionId: "3e54eb54-946e-4ff4-a430-d7b190cd45cf"
  resourceGroup: "node-upgrader"
  clusterName: "lm-cluster"
  retryOnError: false
  testMode: false
  nodePools:
    - name: "centralglas"
      properties: {
        vmSize: "Standard_DS2_v2",
        enableAutoScaling: true,
        orchestratorVersion: "1.28.12",
        minCount: 0,
        maxCount: 5,
        availabilityZones: [ "1" ]
      }
    - name: "servicesglas"
      properties: {
        vmSize: "Standard_DS2_v2",
        enableAutoScaling: true,
        orchestratorVersion: "1.28.12",
        minCount: 0,
        maxCount: 5,
        availabilityZones: [ "1" ]
      }
    - name: "servicesblue"
      properties: {
        vmSize: "Standard_DS2_v2",
        enableAutoScaling: true,
        orchestratorVersion: "1.29.0",
        minCount: 0,
        maxCount: 5,
        availabilityZones: [ "1" ]
      }
    - name: "centralblue"
      properties: {
        vmSize: "Standard_DS2_v2",
        enableAutoScaling: true,
        orchestratorVersion: "1.29.0",
        minCount: 0,
        maxCount: 5,
        availabilityZones: [ "1" ]
      }



