name: Release Charts
on:
  push:
    branches:
      - master
jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Chart
        working-directory: charts/nodepoolmanager
        run: |
          helm package .
          
      - name: Helm Index
        working-directory: charts/nodepoolmanager
        run: |
          curl https://k8smanagers.blob.core.windows.net/helm/index.yaml > index-temp.yaml
          helm repo index --url https://k8smanagers.blob.core.windows.net/helm/ . --merge index-temp.yaml
          mv -f index-temp.yaml index.yaml

      - name: Helm Upload
        working-directory: charts/nodepoolmanager
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
        run: |
          az storage blob upload --container-name helm --file index.yaml --name index.yaml
          az storage blob upload --container-name helm --file *.tgz --name *.tgz
